config/routes.rb
Rails.application.routes.draw do
  POST_TYPES = {
    activity: 'activities',
    article:  'articles',
    bookmark: 'bookmarks',
    event:    'events',
    note:     'notes',
    photo:    'photos',
    sound:    'sounds',
    video:    'videos'
  }.freeze
  YEAR_MONTH_DAY_CONSTRAINTS = { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }.freeze
  PAGINATION_CONSTRAINTS     = { page: /\d+/ }.freeze
  YEAR_MONTH_DAY_PATH        = '/:year/:month/:day'.freeze

  root to: 'root#index'

  # Admin Dashboard
  namespace :admin do
    resources :links # rel-me links
    resources :redirects, except: :show # Redirects Manager
    resources :settings, only: [:index, :edit, :update] # Settings
    resources :tags
  end

  # NEW Post Launchpad
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'new',       to: 'dashboard#new',   as: 'dashboard_new'

  # Posts (Composite Feed) Pagination and RSS/Atom feed
  get 'posts',                    to: 'posts#index', as: 'posts'
  get 'page/1',                   to: redirect('/'), as: 'posts_pagination_redirect_one'
  get 'page',                     to: redirect('/'), as: 'posts_pagination_redirect'
  get 'page/:page',               to: 'posts#index', constraints: PAGINATION_CONSTRAINTS
  get '(/:year)(/:month)(/:day)', to: 'posts#index', constraints: YEAR_MONTH_DAY_CONSTRAINTS
  get 'feed',                     to: 'posts#index', defaults: { format: 'atom' }, as: :feed

  # Users + Auth
  resources :users,    only: [:create, :update, :destroy]
  resources :sessions, only: [:create]
  get 'profile', to: 'users#edit',       as: 'profile'
  get 'signup',  to: 'users#new',        as: 'signup'
  get 'signin',  to: 'sessions#new',     as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  POST_TYPES.each do |singular, plural|
    # RSS/Atom feeds
    get "/#{plural}/feed", to: "#{plural}#index", defaults: { format: 'atom' }, as: "#{plural}_feed"

    # Post CRUD
    get    "#{plural}/new",                              to: "#{plural}#new",    as: "new_#{singular}"
    post   plural.to_s,                                  to: "#{plural}#create", as: plural.to_s
    post   "#{plural}#{YEAR_MONTH_DAY_PATH}",            to: "#{plural}#create",                         constraints: YEAR_MONTH_DAY_CONSTRAINTS
    get    "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug",      to: "#{plural}#show",   as: singular.to_s,      constraints: YEAR_MONTH_DAY_CONSTRAINTS
    get    "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug/edit", to: "#{plural}#edit",   as: "edit_#{singular}", constraints: YEAR_MONTH_DAY_CONSTRAINTS
    patch  "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug",      to: "#{plural}#update",                         constraints: YEAR_MONTH_DAY_CONSTRAINTS
    put    "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug",      to: "#{plural}#update",                         constraints: YEAR_MONTH_DAY_CONSTRAINTS
    delete "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug",      to: "#{plural}#destroy",                        constraints: YEAR_MONTH_DAY_CONSTRAINTS

    # Post Pagination
    get "#{plural}/page/1",                     to: redirect("/#{plural}")
    get "#{plural}/page",                       to: redirect("/#{plural}")
    get "#{plural}/page/:page",                 to: "#{plural}#index", constraints: PAGINATION_CONSTRAINTS
    get "(/#{plural})(/:year)(/:month)(/:day)", to: "#{plural}#index", constraints: YEAR_MONTH_DAY_CONSTRAINTS
  end

  # Syndication
  post 'syndicators/:post_type/:id/:service', to: 'syndicators#create', as: :syndicators

  # Syndication Auth
  get  'auth/:provider/setup',    to: 'providers#setup'
  get  'auth/:provider/callback', to: 'providers#create'
  post 'auth/:provider/callback', to: 'providers#create'

  # Pages CRUD (Articles acting as Pages)
  get 'pages/new',  to: 'pages#new',    as: 'new_page'
  post 'pages',     to: 'pages#create', as: 'pages'
  get 'pages',      to: 'pages#index'
  post ':slug',     to: 'pages#create', constraints: YEAR_MONTH_DAY_CONSTRAINTS
  get ':slug/edit', to: 'pages#edit', as: 'edit_page', constraints: YEAR_MONTH_DAY_CONSTRAINTS
  patch ':slug',    to: 'pages#update',                  constraints: YEAR_MONTH_DAY_CONSTRAINTS
  delete ':slug',   to: 'pages#destroy',                 constraints: YEAR_MONTH_DAY_CONSTRAINTS

  # Site Search
  get 'search', to: 'search#index', as: 'search'

  # Tags
  resources :tags

  # Micropub
  get 'micropub', to: 'about#micropub', as: 'micropub'

  # Site photo / avatar
  get 'photo(.format)', to: 'about#site_photo'

  # PGP/GPG public key
  get 'key.pub', to: 'about#public_key', as: 'public_key'

  # Keybase.io identity proof
  get 'keybase.txt', to: 'about#keybase_proof', as: 'keybase_proof'

  # Redirection and Page lookup as a fallback to all routes
  get ':slug', to: 'pages#show', as: 'page'
end

app/views/admin/_danger_zone.html.erb
<div class="panel panel-danger danger-zone">
  <div class="panel-heading">
    <h3 class="panel-title">Want to delete this <%= label %>?</h3>
  </div>
  <div class="panel-body">
    You can delete this <%= label %> at anytime.
    All of <%= label == "person" ? "their" : "its" %> associated data will be immediately and permanently deleted.
    There is <b>NO UNDO</b>.
  </div>
  <div class="panel-footer actions">
    <%= link_to "Delete", post.path, method: :delete, data: { confirm: "Are you sure you're sure? There is NO UNDO." }, class: "btn btn-danger" %>
  </div>
</div>

app/views/admin/_date_select_row.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4">
    <%= select_year datetime_select_value(thing, attr, :year),
          { prompt: true },
          name:  "#{post_type}[#{attr}(1i)]",
          id:    "#{post_type}_#{attr}_1i",
          class: "form-control datetime-select" %>
  </div>
  <div class="col-xs-12 col-sm-4">
    <%= select_month datetime_select_value(thing, attr, :month),
          { prompt: true },
          name:  "#{post_type}[#{attr}(2i)]",
          id:    "#{post_type}_#{attr}_2i",
          class: "form-control datetime-select" %>
  </div>
  <div class="col-xs-12 col-sm-4">
    <%= select_day datetime_select_value(thing, attr, :day),
          { prompt: true },
          name:  "#{post_type}[#{attr}(3i)]",
          id:    "#{post_type}_#{attr}_3i",
          class: "form-control datetime-select" %>
  </div>
</div>

app/views/admin/_datetime_group.html.erb
<div class="form-group">
  <%= f.label attr %>
  <%= render "admin/date_select_row", thing: thing, post_type: thing.post_type.class.to_s.downcase, attr: attr %>
  <%= render "admin/time_select_row", thing: thing, post_type: thing.post_type.class.to_s.downcase, attr: attr %>
</div>

app/views/admin/_form_actions.html.erb
<%# TODO there's got to be a better way! %>
<% button_text ||= "Publish" %>

<div class="actions">
  <%= link_to "Cancel", cancel_url, class: "cancel" %>
  <%= f.submit button_text , class: "btn btn-success btn-lg" %>
</div>

app/views/admin/_form_content.html.erb
<div class="form-group">
  <%= f.label :content, "Content", class: "sr-only" %>
  <%= f.text_area :content, class: "form-control", rows: 10, placeholder: lorem_ipsum %>
</div>

app/views/admin/_form_errors.html.erb
<% if thing.errors.any? %>
  <% thing.errors.full_messages.uniq.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>.
    </div>
  <% end %>
<% end %>

app/views/admin/_form_image_url.html.erb
<div class="form-group">
  <%= f.label :image_url, "Image URL" %>
  <%= f.url_field :image_url, class: "form-control" %>
</div>

app/views/admin/_form_page_appearance.html.erb
<% if on_page? %>
  <fieldset id="appearance">
    <legend>Appearance</legend>

    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="form-group">
          <%= f.check_box :hide_header %>
          <%= f.label :hide_header, "Hide the Site Header?" %>
          <p class="help-block">
            This will remove the site header/<wbr>nav/<wbr>search/<wbr>etc from this <i>Page</i> only.
          </p>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4">
        <div class="form-group">
          <%= f.check_box :hide_footer %>
          <%= f.label :hide_footer, "Hide the Site Footer?" %>
          <p class="help-block">
            This will remove the site footer from this <i>Page</i> only.
          </p>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4">
        <div class="form-group">
          <%= f.check_box :hide_layout %>
          <%= f.label :hide_layout, "Hide the Site Layout?" %>
          <p class="help-block">
            <b class="text-danger">Danger Zone&trade; &mdash; exercise caution with this option.</b>
            The will remove all of the wrapper layout.
            This <i>Page</i> will be responsible for <i>all</i> of its HTML,
            including <code>&lt;html&gt;</code>, <code>&lt;head&gt;</code>,
            <code>&lt;title&gt;</code>, <code>&lt;body&gt;</code> tags etc.
            Any <code>CSS</code> will have to be included in the
            <code>Content</code>, not the <code>Page Specific CSS</code>.
          </p>
        </div>
      </div>

    </div>
  </fieldset>
<% end %>

app/views/admin/_form_post_meta.html.erb
<fieldset id="meta">
  <legend>Optional Meta</legend>

  <div class="row">
    <div class="col-xs-6">
      <%= render "admin/toggle_group",
                 f:                    f,
                 attr:                 :private,
                 unchecked_label:      "Public #{post_or_page(post)}",
                 checked_label:        "Private #{post_or_page(post)}",
                 unchecked_help_block: "<b>Public  #{post_or_page(post).pluralize}</b> are visible to anyone",
                 checked_help_block:   "<b>Private #{post_or_page(post).pluralize}</b> are only visible to you" %>
    </div>

    <% if on_page? %>
      <div class="col-xs-6">
        <%= render "admin/toggle_group",
                   f:                    f,
                   attr:                 :show_in_nav,
                   unchecked_label:      "Don&rsquo;t show in site navigation",
                   checked_label:        "Show in site  navigation",
                   unchecked_help_block: nil,
                   checked_help_block:   "<b>Private Pages</b> are only in site navigation for you." %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :in_reply_to, "In Reply To" %>
    <%= f.text_field :in_reply_to, class: "form-control", placeholder: "http://example.com http://example.net" %>
    <p class="help-block">Space separated URLs</p>
  </div>

  <div class="row">
    <div class="form-group col-sm-6">
      <%= f.label :slug, "URL Slug" %>
      <%= f.text_field :slug, class: "form-control" %>
      <p class="help-block">Auto-generated if left blank</p>
    </div>

    <div class="form-group col-sm-6">
      <%= f.label :tags %>
      <%= text_field_tag :tags, post.tags.map{|t| t.display_name}.join(", "), class: "form-control", placeholder: "cats, dogs, bunny rabbits" %>
      <p class="help-block">Comma separated</p>
    </div>
  </div>

  <%= render "admin/datetime_group", f: f, attr: :published_at, thing: post %>
</fieldset>

app/views/admin/_form_title_subtitle.html.erb
<div class="form-group">
  <%= f.label :title, class: "sr-only" %>
  <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
</div>

<div class="form-group">
  <%= f.label :subtitle, class: "sr-only" %>
  <%= f.text_field :subtitle, class: "form-control", placeholder: "Subtitle" %>
</div>

app/views/admin/_nav.html.erb
<% if signed_in? %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">

      <%= link_to root_path, rel: "home", class: "navbar-brand pull-left" do %>
        <%= image_tag setting(:touch_icon_url_57x57), alt: "Site avatar" %>
      <% end %>

      <div class="hidden-xs">
        <form action="/search" method="get" class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="search" name="q" class="form-control" placeholder="Search site">
          </div>
          <button type="submit" class="btn btn-default sr-only">Submit</button>
        </form>
      </div>

      <div class="navbar-right pull-right">
        <%= link_to "Dashboard", dashboard_path, class: "btn btn-default navbar-btn" %>
        <%= link_to "NEW", dashboard_new_path, class: "btn btn-primary navbar-btn" %>
      </div>

    </div><!-- /.container -->
  </nav>

  <div class="visible-xs-block">
    <div class="container">
      <form action="/search" method="get" role="search">
        <div class="form-group">
          <input type="search" name="q" class="form-control" placeholder="Search site">
        </div>
        <button type="submit" class="btn btn-default sr-only">Submit</button>
      </form>
    </div>
  </div>
<% end %>

app/views/admin/_notifications.html.erb
<div id="notifications">
  <% if flash[:notice] %><div class="container"><div class="alert alert-info">  <%= flash[:notice].html_safe %></div></div><% end %>
  <% if flash[:alert]  %><div class="container"><div class="alert alert-danger"><%= flash[:alert].html_safe  %></div></div><% end %>
</div>

app/views/admin/_time_select_row.html.erb
<div class="row">
  <div class="col-xs-6 published-at-hour">
    <%= select_hour datetime_select_value(thing, attr, :hour),
          { prompt: true },
          name:  "#{post_type}[#{attr}(4i)]",
          id:    "#{post_type}_#{attr}_4i",
          class: "form-control datetime-select" %>
  </div>
  <div class="col-xs-6">
    <%= select_minute datetime_select_value(thing, attr, :min),
          { prompt: true },
          name:  "#{post_type}[#{attr}(5i)]",
          id:    "#{post_type}_#{attr}_5i",
          class: "form-control datetime-select" %>
  </div>
</div>

app/views/admin/_toggle_group.html.erb
<div class="form-group toggle-group">
  <%= f.check_box attr, class: "form-control" %>

  <%= f.label attr do %>
    <span class="btn btn-default toggle-unchecked"><%= raw unchecked_label %></span>
    <span class="btn btn-default   toggle-checked"><%= raw checked_label   %></span>
  <% end %>

  <p class="help-block">
    <span class="toggle-unchecked"><%= raw unchecked_help_block %></span>
    <span class="toggle-checked  "><%= raw   checked_help_block %></span>
  </p>
</div>