config/routes.rb
Rails.application.routes.draw do
  POST_TYPES = {
    activity: 'activities',
    article:  'articles',
    bookmark: 'bookmarks',
    event:    'events',
    note:     'notes',
    photo:    'photos',
    sound:    'sounds',
    video:    'videos'
  }.freeze
  YEAR_MONTH_DAY_CONSTRAINTS = { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }.freeze
  PAGINATION_CONSTRAINTS     = { page: /\d+/ }.freeze
  YEAR_MONTH_DAY_PATH        = '/:year/:month/:day'.freeze

  root to: 'root#index'

  # Admin Dashboard
  namespace :admin do
    resources :links # rel-me links
    resources :redirects, except: :show # Redirects Manager
    resources :settings, only: [:index, :edit, :update] # Settings
    resources :tags
  end

  # NEW Post Launchpad
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'new',       to: 'dashboard#new',   as: 'dashboard_new'

  # Posts (Composite Feed) Pagination and RSS/Atom feed
  get 'posts',                    to: 'posts#index', as: 'posts'
  get 'page/1',                   to: redirect('/'), as: 'posts_pagination_redirect_one'
  get 'page',                     to: redirect('/'), as: 'posts_pagination_redirect'
  get 'page/:page',               to: 'posts#index', constraints: PAGINATION_CONSTRAINTS
  get '(/:year)(/:month)(/:day)', to: 'posts#index', constraints: YEAR_MONTH_DAY_CONSTRAINTS
  get 'feed',                     to: 'posts#index', defaults: { format: 'atom' }, as: :feed

  # Users + Auth
  resources :users,    only: [:create, :update, :destroy]
  resources :sessions, only: [:create]
  get 'profile', to: 'users#edit',       as: 'profile'
  get 'signup',  to: 'users#new',        as: 'signup'
  get 'signin',  to: 'sessions#new',     as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  POST_TYPES.each do |singular, plural|
    # RSS/Atom feeds
    get "/#{plural}/feed", to: "#{plural}#index", defaults: { format: 'atom' }, as: "#{plural}_feed"

    # Post CRUD
    get    "#{plural}/new",                              to: "#{plural}#new",    as: "new_#{singular}"
    post   plural.to_s,                                  to: "#{plural}#create", as: plural.to_s
    post   "#{plural}#{YEAR_MONTH_DAY_PATH}",            to: "#{plural}#create",                         constraints: YEAR_MONTH_DAY_CONSTRAINTS
    get    "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug",      to: "#{plural}#show",   as: singular.to_s,      constraints: YEAR_MONTH_DAY_CONSTRAINTS
    get    "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug/edit", to: "#{plural}#edit",   as: "edit_#{singular}", constraints: YEAR_MONTH_DAY_CONSTRAINTS
    patch  "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug",      to: "#{plural}#update",                         constraints: YEAR_MONTH_DAY_CONSTRAINTS
    put    "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug",      to: "#{plural}#update",                         constraints: YEAR_MONTH_DAY_CONSTRAINTS
    delete "#{plural}#{YEAR_MONTH_DAY_PATH}/:slug",      to: "#{plural}#destroy",                        constraints: YEAR_MONTH_DAY_CONSTRAINTS

    # Post Pagination
    get "#{plural}/page/1",                     to: redirect("/#{plural}")
    get "#{plural}/page",                       to: redirect("/#{plural}")
    get "#{plural}/page/:page",                 to: "#{plural}#index", constraints: PAGINATION_CONSTRAINTS
    get "(/#{plural})(/:year)(/:month)(/:day)", to: "#{plural}#index", constraints: YEAR_MONTH_DAY_CONSTRAINTS
  end

  # Syndication
  post 'syndicators/:post_type/:id/:service', to: 'syndicators#create', as: :syndicators

  # Syndication Auth
  get  'auth/:provider/setup',    to: 'providers#setup'
  get  'auth/:provider/callback', to: 'providers#create'
  post 'auth/:provider/callback', to: 'providers#create'

  # Pages CRUD (Articles acting as Pages)
  get 'pages/new',  to: 'pages#new',    as: 'new_page'
  post 'pages',     to: 'pages#create', as: 'pages'
  get 'pages',      to: 'pages#index'
  post ':slug',     to: 'pages#create', constraints: YEAR_MONTH_DAY_CONSTRAINTS
  get ':slug/edit', to: 'pages#edit', as: 'edit_page', constraints: YEAR_MONTH_DAY_CONSTRAINTS
  patch ':slug',    to: 'pages#update',                  constraints: YEAR_MONTH_DAY_CONSTRAINTS
  delete ':slug',   to: 'pages#destroy',                 constraints: YEAR_MONTH_DAY_CONSTRAINTS

  # Site Search
  get 'search', to: 'search#index', as: 'search'

  # Tags
  resources :tags

  # Micropub
  get 'micropub', to: 'about#micropub', as: 'micropub'

  # Site photo / avatar
  get 'photo(.format)', to: 'about#site_photo'

  # PGP/GPG public key
  get 'key.pub', to: 'about#public_key', as: 'public_key'

  # Keybase.io identity proof
  get 'keybase.txt', to: 'about#keybase_proof', as: 'keybase_proof'

  # Redirection and Page lookup as a fallback to all routes
  get ':slug', to: 'pages#show', as: 'page'
end

app/views/shared/_backward_compatibility_meta_tags.html.erb
<% if setting(:google_site_verification).present? %>
  <!-- Google Site Verification for WebMaster tools -->
  <meta name="google-site-verification" content="<%= setting :google_site_verification %>" />
<% end %>

<% if false %>
  <!-- Micropub -->
  <link rel="me"                     href="<%= setting :rel_me %>" />
  <link rel="authorization_endpoint" href="<%= setting :rel_authorization_endpoint %>" />
  <link rel="token_endpoint"         href="<%= setting :rel_token_endpoint %>" />
  <link rel="micropub"               href="/micropub %>" />
<% end %>

<!-- Backward compatibility: Facebook (Open Graph) -->
<meta property="og:type"         content="blog" />
<meta property="og:url"          content="<%= canonical_url @post %>" />
<meta property="og:image"        content="<%#= "TODO" %>" />
<meta property="og:title"        content="<%= site_title %>" />
<meta property="og:description"  content="<%= page_description %>" />
<meta property="fb:app_id"       content="<%#= "TODO" %>" />

<% if false %>
<!-- Backward compatibility: Twitter Cards -->
  
<% end %>

app/views/shared/_fav_and_touch_icons.html.erb
<!-- Fav and touch icons -->
<link rel="shortcut icon" href="<%= setting :favicon_url_16x16_or_32x32 %>" />
<%= apple_touch_icon_link_tags %>
<link rel="icon" sizes="192x192" href="<%= setting :touch_icon_url_192x192 %>" />

app/views/shared/_google_site_search.html.erb
<form action="/search" method="get" class="search form-inline" role="search">
  <div class="form-group">
    <input type="search" name="q" class="form-control" placeholder="Site search">
  </div>
  <button type="submit" class="btn btn-default sr-only">SEARCH</button>
</form>

app/views/shared/_javascripts.html.erb
<!-- JS -->
<% if on_admin_page? %>
  <%= javascript_include_tag "admin" %>
<% end %>

app/views/shared/_license.html.erb
<%# This spacing is to make view source license comment very readable %>

  <!--
    *************************************************************
    <%= license %>
    **************************************************************
  -->

app/views/shared/_link_tags.html.erb
<!-- Backward compatibility: RSS/Atom -->
<%= auto_discovery_link_tag(:atom, feed_path, title: setting(:site_title)) %>

<!-- Canonical URLs -->
<%= rel_canonical_link_tag @post %>
<%#= shorturl_link_tag      @post %>
<% if public_key? %><link rel="pgpkey" href="/key.pub" /><% end %>

app/views/shared/_meta_tags.html.erb
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- General meta tags -->
<meta name="application-name"    content="<%= site_title %>" />
<meta name="description"         content="<%= page_description %>" />
<meta name="generator"           content="Dark Matter Publisher 0.3.0 (darkmatterapp.com)" />

<%= csrf_meta_tags %>

app/views/shared/_site_footer.html.erb
<% unless on_page? && @post.hide_footer %>

  <footer role="contentinfo">
    <%= render "shared/google_site_search" if show?(:footer_show_site_search) %>

    <div class="h-card">
      <%= render "shared/site_owner_photo" if show?(:footer_show_avatar) %>

      <% unless @owner.nil?  %>
        <p>
          <% unless @owner.try(:name) && show?(:footer_show_name) && show?(:footer_show_email) %>
            <strong>Contact:</strong>
          <% end %>

          <% unless @owner.name.blank? || hide?(:footer_show_name) %>
            <%= link_to @owner.name, root_url, class: "u-url p-name", rel: "home" %>
          <% end %>

          <% unless @owner.phone.blank? || hide?(:footer_show_phone_number) %>
            <%= link_to @owner.phone, "tel://#{@owner.phone.gsub(/\D/, "")}", class: "u-tel" %>
          <% end %>

          <% unless @owner.email.blank? || hide?(:footer_show_email) %>
            <%= mail_to @owner.email, @owner.email, class: "u-email" %>
          <% end %>

          <% unless @owner.email.blank? || hide?(:footer_show_email) || hide?(:footer_show_email_vcard_link) %>
            (<%= link_to "Download vCard", "http://h2vx.com/vcf/#{setting :domain}", class: "u-url" %>)
          <% end %>
        </p>

        <% unless @owner.links.blank? || hide?(:footer_show_links) %>
          <p>
            <strong>Links:</strong>
            <% @owner.links.each do |link| %>
              <%= link_to link.name, link.url, rel: "me", class: "u-url" %>
            <% end %>
          </p>
        <% end %>
      <% end %>
    </div>

    <% if show?(:footer_show_license) %>
      <p><%= license :html %>.</p>
    <% end %>
  </footer>

<% end %>

app/views/shared/_site_header.html.erb
<% if signed_in? %>
  <div id="admin-button">
    <%= link_to "Admin Dashboard", dashboard_new_path %>
  </div>
<% end %>

<% unless on_page? && @post.hide_header %>
  <header role="banner">
    <%= render "shared/site_owner_photo" if show?(:header_show_avatar) %>

    <h1 class="dm-site-title"><%= link_to setting(:site_title), root_url, rel: "home" if show?(:header_show_site_title) %></h1>
    <div class="dm-site-description"><%= simple_format setting(:site_description) if show?(:header_show_site_description) %></div>
  </header>
<% end %>

app/views/shared/_site_nav.html.erb
<% unless on_page? && @post.hide_header %>

  <nav role="navigation">
    <% if allow_signup? %>
      <%= link_to "Sign Up", signup_path %>
    <% else %>
      <ul>
        <% if show_nav_to?(:home) %><li><%= link_to "Home", root_path, rel: "home" %></li><% end %>
        <% if show_site_nav? %>
          <% if Setting.of("home_page").content.present? %>
            <li><%= link_to "Posts", posts_path %></li>
          <% end %>

          <% if show_nav_to?(:articles) %><li><%= link_to "Articles", articles_path %></li><% end %>
          <% if show_nav_to?(:bookmarks) %><li><%= link_to "Bookmarks", bookmarks_path %></li><% end %>
          <% if show_nav_to?(:events) %><li><%= link_to "Events", events_path %></li><% end %>
          <% if show_nav_to?(:notes) %><li><%= link_to "Notes", notes_path %></li><% end %>
          <% if show_nav_to?(:photos) %><li><%= link_to "Photos", photos_path %></li><% end %>
          <% if show_nav_to?(:sounds) %><li><%= link_to "Sounds", sounds_path %></li><% end %>
          <% if show_nav_to?(:videos) %><li><%= link_to "Videos", videos_path %></li><% end %>
          <% if show_nav_to?(:pages) %><li><%= link_to "Pages", pages_path %></li><% end %>
          <% if show_nav_to?(:activities) %><li><%= link_to "Activities", activities_path %></li><% end %>
        <% end %>

        <% @page_links.each do |page| %>
          <li><%= link_to page.title, page.path %></li>
        <% end %>
      </ul>
    <% end %>
  </nav>

  <%= render "shared/google_site_search" if show?(:header_show_site_search) %>

<% end %>

app/views/shared/_site_owner_photo.html.erb
<% if @owner && !@owner.avatar.blank? %>
  <%= link_to image_tag(site_photo_path, class: "u-photo"), root_url, class: "u-url", rel: "home" %>
<% end %>

app/views/shared/_stylesheets.html.erb
<!-- CSS -->
<% if on_admin_page? %>
  <%= stylesheet_link_tag "admin",       media: "all" %>
<% else %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <!-- Custom CSS -->
  <style><%= setting :custom_css %></style>
<% end %>